### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Mogaetsho10** [NicholasMetro/Hearing-Test#4]
Hi, I'm relatively new to Android programming. Is it possible to provide detailed steps on how to implement this using Android Studio. Thank you.

**Comment by jimmyblaszkiewicz** [comment]
Hi,
This was an 11th grade project for a Java class. The base functionality is as follows:
Play a sound,
User clicks a button when they hear the sound,
Quantify the response time and score out of 150 points.

I have no experience with Android Studio, but I imagine it would not be too difficult to perform the above steps. I would not recommend working off of this repository, as much of the code does not follow traditional or recommended programming standards.

**Comment by Mogaetsho10** [comment]
Alright, thank you. Do you know anyone who has tried to solve this problem using Android Studio?
